[package]
name = "skate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-ssh2-tokio = { version = "0.8.1", features = ["openssl"]}
async-trait = "0.1.74"
clap = { version = "4.4.7", features = ["derive", "env"] }
futures = "0.3.29"
k8s-openapi = { version = "0.20.0", features = ["latest"] }
semver = "1.0.20"
serde = { version = "1.0.190", features = ["derive"] }
serde_yaml = "0.9.27"
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }
openssl = { version = "0.10.35", features = ["vendored"] }
itertools = "0.11.0"
path-absolutize = "3.1.1"
shellexpand = "3.1.0"
serde_json = "1.0.108"
deunicode = "1.4.1"
sysinfo = "0.29.10"
