[target.x86_64-unknown-linux-gnu]
pre-build = [                                  # additional commands to run prior to building the package
    "apt-get update && apt-get install -y wget unzip",
    "wget https://github.com/protocolbuffers/protobuf/releases/download/v27.3/protoc-27.3-linux-x86_64.zip -O /tmp/protoc.zip",
    "cd /tmp && unzip protoc.zip",
    "mv /tmp/bin/protoc /usr/local/bin/protoc",
]
[target.aarch64-unknown-linux-gnu]
pre-build = [                                  # additional commands to run prior to building the package
    "apt-get update && apt-get install -y wget unzip",
    "wget https://github.com/protocolbuffers/protobuf/releases/download/v27.3/protoc-27.3-linux-aarch_64.zip -O /tmp/protoc.zip",
    "cd /tmp && unzip protoc.zip",
    "mv /tmp/bin/protoc /usr/local/bin/protoc",
]
