---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns
  namespace: skate
  labels:
    app: coredns
spec:
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      volumes:
      - name: skate
        hostPath:
          path: /etc/skate
      containers:
      - name: coredns
        image: ghcr.io/skateco/coredns
        volumeMounts:
        - mountPath: /etc/skate
          name: skate
        env:
        - name: CORE_FILE
          value: |
            cluster.skate:53 {
                hosts /run/containers/cni/dnsname/podman/addnhosts {
                    fallthrough
                }
            
                errors {
                  consolidate 5m ".*" warning
                }
            }
            .:53 {
                forward . 8.8.8.8
                log
                errors
                cache
            }

