---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns
  namespace: skate
  labels:
    app: coredns
spec:
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      hostNetwork: true
      volumes:
      - name: cni
        hostPath:
          path: /var/lib/skate/dns
      containers:
      - name: coredns
        image: ghcr.io/skateco/coredns
        volumeMounts:
        - mountPath: /var/lib/skate/dns
          name: cni
        env:
        - name: CORE_FILE
          value: |
            cluster.skate:5553 {
            
                bind lo 0.0.0.0
            
                hosts /var/lib/skate/dns/addnhosts
            }
            
            cluster.skate:53 {
            
                bind lo
            
                fanout . %%fanout_list%%
            
                loadbalance round_robin
            
            }
            .:53 {
                bind lo 0.0.0.0
                forward . 8.8.8.8
            }

