---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns
  namespace: skate
  labels:
    app: coredns
spec:
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      hostNetwork: true
      volumes:
      - name: cni
        hostPath:
          path: /var/lib/skate/dns
      containers:
      - name: coredns
        image: ghcr.io/skateco/coredns@sha256:3dbd9667b98d4d97fd320da0ec5da56ed65ccf20f12e732a4e1ff38024eff569
        volumeMounts:
        - mountPath: /var/lib/skate/dns
          name: cni
        env:
        - name: CORE_FILE
          value: |
            cluster.skate:5553 {
            
                bind lo 0.0.0.0
            
                hosts /var/lib/skate/dns/addnhosts
            }
            
            svc.cluster.skate:53 {
                
                    bind lo
                
                    hosts /var/lib/skate/dns/addnhosts
                
            }
            
            pod.cluster.skate:53 {
            
                bind lo
            
                fanout . %%fanout_list%%
            
                loadbalance round_robin
            
            }
            .:53 {
                bind lo 0.0.0.0
                forward . 8.8.8.8
            }

