---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: foo
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        x: y
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
#        ports:
#        - containerPort: 8000
---
