---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: foo
  labels:
    app: nginxy
spec:
  selector:
    matchLabels:
      app: nginxy
  template:
    metadata:
      labels:
        app: nginxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
---
