name: Check compilation

on:
  push:
    # only trigger on branches, not on tags
    branches: '**'

jobs:
  check:  # Any action can contain multiple jobs
    runs-on: ubuntu-latest  # OS on which the job runs
    steps:  # Each job consists in a series of steps
    - name: Checkout  # Clone git repository
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check that code can compile
      run: cargo check  # Run the `cargo check` command
    - name: Compile
      run: cargo build
