name: Release

permissions:
  contents: write

on:
  push:
    tags:
    - v[0-9]+.*

jobs:
  create-release:
    strategy:
      matrix:
        include:
        - target: aarch64-apple-darwin
          os: macos-latest
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/create-gh-release-action@v1
      with:
        # (optional) Path to changelog.
#        changelog: CHANGELOG.md
        # (required) GitHub token for creating GitHub Releases.
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: "${{ matrix.target }}"
    - name: Setup Cache
      uses: Swatinem/rust-cache@v2
    - if: target.os == 'ubuntu-latest'
      name: Install Dependencies
      run: sudo apt-get install -y protobuf-compiler libprotobuf-dev
    - name: Build Binary
      run: cargo build --verbose --locked --release --target ${{ matrix.target }}
